### ISSUE TITLE
each bulb

### ISSUE THREAD

**Issue by hamed-jamali-software** [akashcraft/LED-Controller#1]
Is this different for each bulb?

**Comment by akashcraft** [comment]
So this is intended for LED Strips that contain the IR and Bluetooth receiver. There is no support for Smart Bulbs. Currently, it supports only a specific model of strips like the one linked in `README.md`. I am working on adding a Settings section where you can change the op codes and mac addresses for different strip models. You can play around with the code to change the hard coded lines for those settings.

**Comment by akashcraft** [comment]
Done building the application!
